var changeDirectonBtn=document.getElementById("change-direction");
window.addEventListener('load',getLocalStorage);
var elementFloatleft=document.querySelectorAll(".ml-auto ,.float-left");
var elementTxtAlign=document.querySelectorAll(".text-left")
var elementFloatRight=document.querySelectorAll(".float-right")
// console.log(elementFloatleft)
var dataArabic={
    "SubscribeCost":"الاشتراك",
    "ADINFO":"معلومات الإعلان",
    "CompanyEnglishName:":"اسم الشركة الإنجليزية:",
    "CompanyArabicName:":"اسم الشركة العربية:",
    "ADCategory:":"ملف الاعلانات الرئيسية :",
    "ADSubCategory:":"ملف الاعلانات الفرعية:",
    "Country:":"بلد:",
    "EmployeeNumber:":"رقم الموظف:",
    "EmployeeName:":"اسم الموظف:",
    "CR":"سجل تجاري",
    "VATID":"شهاده الضربية",
    "LogoFile":"ملف الشعار",
    "DesginFile":"ملف التصميم",
    "DesginFile2":"اضافه ملف",
    "OWNERiNFORMATION":"هوية المالك",
    "ADDETAILS":"تفاصيل الإعلان",
    "ADEnglishDescription:":"وصف الاعلان بالغة الانجليزية:",
    "ADArabicDescription:":"وصف الاعلان بالغة العربية:",
    "Keywords:":"الكلمات الدالة:",
    "AvailableJobs:":"الوظائف المتاحة:",
    "AddJobs:":"اضافه الوظائف الاخري :",
    "ADDITIONALINFO":"معلومات إضافية",
    "Mobile":"الجوال",
    "Phone":"الهاتف",
    "E-mail":"الايميل",
    "Website":"موقع الكتروني",
    "FullAddressEnglish":"العنوان بالكامل بالانجليزي",
    "FullAddressArabic":"العنوان بالكامل بالعربي",
    "Facebook":"Facebook",
    "Twitter":"Twitter",
    "Instagram":"Instagram",
    "LinkedIn":"Linked In",
    "Youtube":"Youtube",
    "Snapchat":"Snapchat",
    "Login":"إرسال",
    "companyname:":"اسم شركة التسويق:",
     "Country":"بلد",
    "Afghanistan":"أفغانستان",
    "ÅlandIslands":"جزر آلاند",
    "Albania":"ألبانيا",
    "Algeria":"الجزائر",
    "AmericanSamoa":"ساموا الأمريكية",
    "Andorra":"أندورا",
    "Angola":"أنغولا",
    "Anguilla":"أنغيلا",
    "Antarctica":"القارة القطبية الجنوبية",
    "AntiguaandBarbuda":"أنتيغوا وبربودا",
    "Argentina":"الأرجنتين",
    "Armenia":"أرمينيا",
    "Aruba":"أروبا",
    "Australia":"أستراليا",
    "Austria":"النمسا",
    "Azerbaijan":"أذربيجان",
    "Bahamas":"الباهاما",
    "Bahrain":"البحرين",
    "Bangladesh":"بنغلاديش",
    "Barbados":"بربادوس",
    "Belarus":"روسيا البيضاء",
    "Belgium":"بلجيكا",
    "Belize":"بليز",
    "Benin":"بنين",
    "Bermuda":"برمودا",
    "Bhutan":"بوتان",
    "Bolivia":"بوليفيا",
    "BosniaandHerzegovina":"البوسنة والهرسك",
    "Botswana":"بوتسوانا",
    "BouvetIsland":"جزيرة بوفيت",
    "Brazil":"البرازيل",
    "BritishIndianOceanTerritory":"إقليم المحيط البريطاني الهندي",
    "BruneiDarussalam":"بروناي دار السلام",
    "Bulgaria":"بلغاريا",
    "BurkinaFaso":"بوركينا فاسو",
    "Burundi":"بوروندي",
    "Cambodia":"كمبوديا",
    "Cameroon":"الكاميرون",
    "Canada":"كندا",
    "CapeVerde":"الرأس الأخضر",
    "CaymanIslands":"جزر كايمان",
    "CentralAfricanRepublic":"جمهورية افريقيا الوسطى",
    "Chad":"تشاد",
    "Chile":"تشيلي",
    "China":"الصين",
    "ChristmasIsland":"جزيرة الكريسماس",
    "Cocos (Keeling) Islands":"جزر كوكوس كيلينغ",
    "Colombia":"كولومبيا",
    "Comoros":"جزر القمر",
    "Congo":"الكونغو",
    "Congo, The Democratic Republic of The":"جمهورية الكونغو الديمقراطية",
    "Cook Islands":"جزر كوك",
    "Costa Rica":"كوستا ريكا",
    "Cote D'ivoire":"كوت ديفوار",
    "Croatia":"كرواتيا",
    "Cuba":"كوبا",
    "Cyprus":"قبرص",
    "Czech Republic":"جمهورية التشيك",
    "Denmark":"الدنمارك",
    "Djibouti":"جيبوتي",
    "Dominica":"دومينيكا",
    "Dominican Republic":"جمهورية الدومنيكان",
    "Ecuador":"الإكوادور",
    "Egypt":"مصر",
    "El Salvador":"السلفادور",
    "Equatorial Guinea":"غينيا الإستوائية",
    "Eritrea":"إريتريا",
    "Estonia":"استونيا",
    "Ethiopia":"أثيوبيا",
    "Falkland Islands (Malvinas)":"جزر فوكلاند مالفيناس",
    "Faroe Islands":"جزر فاروس",
    "Fiji":"فيجي",
    "Finland":"فنلندا",
    "France":"فرنسا",
    "French Guiana":"غيانا الفرنسية",
    "French Polynesia":"بولينيزيا الفرنسية",
    "French Southern Territories":"المناطق الجنوبية لفرنسا",
    "Gabon":"الغابون",
    "Gambia":"غامبيا",
    "Georgia":"جورجيا",
    "Germany":"ألمانيا",
    "Ghana":"غانا",
    "Gibraltar":"جبل طارق",
    "Greece":"اليونان",
    "Greenland":"الأرض الخضراء",
    "Grenada":"غرينادا",
    "Guadeloupe":"جوادلوب",
    "Guam":"غوام",
    "Guatemala":"غواتيمالا",
    "Guernsey":"غيرنسي",
    "Guinea":"غينيا",
    "Guinea-bissau":"غينيا بيساو",
    "Guyana":"غيانا",
    "Haiti":"هايتي",
    "Heard Island and Mcdonald Islands":"قلب الجزيرة وجزر ماكدونالز",
    "Holy See (Vatican City State)":"الكرسي الرسولي دولة الفاتيكان",
    "Honduras":"هندوراس",
    "Hong Kong":"هونج كونج",
    "Hungary":"هنغاريا",
    "Iceland":"أيسلندا",
    "India":"الهند",
    "Indonesia":"إندونيسيا",
    "Iran, Islamic Republic of":"جمهورية إيران الإسلامية",
    "Iraq":"العراق",
    "Ireland":"أيرلندا",
    "Isle of Man":"جزيرة آيل",
    "Israel":"إسرائيل",
    "Italy":"إيطاليا",
    "Jamaica":"جامايكا",
    "Japan":"اليابان",
    "Jersey":"جيرسي",
    "Jordan":"الأردن",
    "Kazakhstan":"كازاخستان",
    "Kenya":"كينيا",
    "Kiribati":"كيريباس",
    "Korea, Democratic People's Republic of":"كوريا، الجمهورية الشعبية الديمقراطية",
    "Korea, Republic of":"جمهورية كوريا",
    "Kuwait":"الكويت",
    "Kyrgyzstan":"قرغيزستان",
    "Lao People's Democratic Republic":"جمهورية لاو الديمقراطية الشعبية",
    "Latvia":"لاتفيا",
    "Lebanon":"لبنان",
    "Lesotho":"ليسوتو",
    "Liberia":"ليبيريا",
    "Libyan Arab Jamahiriya":"الجماهيرية العربية الليبية",
    "Liechtenstein":"ليختنشتاين",
    "Lithuania":"ليتوانيا",
    "Luxembourg":"لوكسمبورغ",
    "Macao":"ماكاو",
    "Macedonia, The Former Yugoslav Republic of":"جمهورية مقدونيا اليوغوسلافية السابقة",
    "Madagascar":"مدغشقر",
    "Malawi":"مالاوي",
    "Malaysia":"ماليزيا",
    "Maldives":"جزر المالديف",
    "Mali":"مالي",
    "Malta":"مالطا",
    "Marshall Islands":"جزر مارشال",
    "Martinique":"مارتينيك",
    "Mauritania":"موريتانيا",
    "Mauritius":"موريشيوس",
    "Mayotte":"مايوت",
    "Mexico":"المكسيك",
    "Micronesia, Federated States of":"ولايات ميكرونيزيا الموحدة",
    "Moldova, Republic of":"جمهورية مولدوفا",
    "Monaco":"موناكو",
    "Mongolia":"منغوليا",
    "Montenegro":"الجبل الأسود",
    "Montserrat":"مونتسيرات",
    "Morocco":"المغرب",
    "Mozambique":"موزمبيق",
    "Myanmar":"ميانمار",
    "Namibia":"ناميبيا",
    "Nauru":"ناورو",
    "Nepal":"نيبال",
    "Netherlands":"هولندا",
    "Netherlands Antilles":"جزر الأنتيل الهولندية",
    "New Caledonia":"كاليدونيا الجديدة",
    "New Zealand":"نيوزيلاندا",
    "Nicaragua":"نيكاراغوا",
    "Niger":"النيجر",
    "Nigeria":"نيجيريا",
    "Niue":"نيوي",
    "Norfolk Island":"جزيرة نورفولك",
    "Northern Mariana Islands":"جزر مريانا الشمالية",
    "Norway":"النرويج",
    "Oman":"سلطنة عمان",
    "Pakistan":"",
    "Palau":"باكستان",
    "Palestinian Territory, Occupieds":"الأراضي الفلسطينية المحتلة",
    "Panama":"بناما",
    "Papua New Guinea":"بابوا غينيا الجديدة",
    "Paraguay":"باراغواي",
    "Peru":"بيرو",
    "Philippines":"الفلبين",
    "Pitcairn":"بيتكيرن",
    "Poland":"بولندا",
    "Portugal":"البرتغال",
    "Puerto Rico":"بورتوريكو",
    "Qatar":"دولة قطر",
    "Reunion":"شمل",
    "Romania":"رومانيا",
    "Russian Federation":"الاتحاد الروسي",
    "Rwanda":"رواندا",
    "Saint Helena":"سانت هيلانة",
    "Saint Kitts and Nevis":"سانت كيتس ونيفيس",
    "Saint Lucia":"القديسة لوسيا",
    "Saint Pierre and Miquelon":"سانت بيير وميكلون",
    "Saint Vincent and The Grenadines":"سانت فنسنت وجزر غرينادين",
    "Samoa":"ساموا",
    "San Marino":"سان مارينو",
    "Sao Tome and Principe":"ساو تومي وبرينسيبي",
    "Saudi Arabia":"المملكة العربية السعودية",
    "Senegal":"السنغال",
    "Serbia":"صربيا",
    "Seychelles":"سيشيل",
    "Sierra Leone":"سيرا ليون",
    "Singapore":"سنغافورة",
    "Slovakia":"سلوفاكيا",
    "Slovenia":"سلوفينيا",
    "Solomon Islands":"جزر سليمان",
    "Somalia":"الصومال",
    "South Africa":"جنوب أفريقيا",
    "South Georgia and The South Sandwich Islands":"جورجيا الجنوبية وجزر ساندويتش الجنوبية",
    "Spain":"إسبانيا",
    "Sri Lanka":"سيريلانكا",
    "Sudan":"السودان",
    "Suriname":"سورينام",
    "Svalbard and Jan Mayen":"سفالبارد وجان ماين",
    "Swaziland":"سوازيلاند",
    "Sweden":"السويد",
    "Switzerland":"سويسرا",
    "Syrian Arab Republic":"الجمهورية العربية السورية",
    "Taiwan, Province of China":"مقاطعة تايوان الصينية",
    "Tajikistan":"طاجيكستان",
    "Tanzania, United Republic of":"جمهورية تنزانيا المتحدة",
    "Thailand":"تايلاند",
    "Timor-leste":"تيمور الشرقية",
    "Togo":"توجو",
    "Tokelau":"توكيلاو",
    "Tonga":"تونغا",
    "Trinidad and Tobago":"ترينداد وتوباغو",
    "Tunisia":"تونس",
    "Turkey":"تركيا",
    "Turkmenistan":"تركمانستان",
    "Turks and Caicos Islands":"جزر تركس وكايكوس",
    "Tuvalu":"توفالو",
    "Uganda":"أوغندا",
    "Ukraine":"أوكرانيا",
    "United Arab Emirates":"الإمارات العربية المتحدة",
    "United Kingdom":"المملكة المتحدة",
    "United States":"الولايات المتحدة الأمريكية",
    "United States Minor Outlying Islands":"جزر الولايات المتحدة البعيدة الصغرى",
    "Uruguay":"أوروغواي",
    "Uzbekistan":"أوزبكستان",
    "Vanuatu":"فانواتو",
    "Venezuela":"فنزويلا",
    "Viet Nam":"فييت نام",
    "Virgin Islands, British":"جزر العذراء البريطانية",
    "Virgin Islands, U.S.":"جزر فيرجن ، الولايات المتحدة",
    "Wallis and Futuna":"واليس وفوتونا",
    "Western Sahara":"الصحراء الغربية",
    "Yemen":"اليمن",
    "Zambia":"زامبيا",
    "Zimbabwe":"زيمبابوي",
                    }
var dataEnglish={
    "SubscribeCost":"Subscribe",
    "ADINFO":"AD INFO",
    "CompanyEnglishName:":"Company English Name:",
    "CompanyArabicName:":"Company Arabic Name:",
    "ADCategory:":"AD Category:",
    "ADSubCategory:":"AD SubCategory:",
    "Country:":"Country:",
    "EmployeeNumber:":"Employee Number:",
    "EmployeeName:":"Employee Name:",
    "CR":"CR",
    "VATID":"VAT ID",
    "OWNERiNFORMATION":"OWNER ID",
    "LogoFile":"Logo File",
    "DesginFile":"Desgin File",
    "DesginFile2":"ADD File",
    "ADDETAILS":"AD DETAILS",
    "ADEnglishDescription:":"AD English Description:",
    "ADArabicDescription:":"AD Arabic Description:",
    "Keywords:":"Keywords:",
    "AvailableJobs:":"Available Jobs:",
    "AddJobs:":"Add Jobs:",
    "ADDITIONALINFO":"ADDITIONAL INFO",
    "Mobile":"Mobile",
    "Phone":"Phone",
    "E-mail":"E-mail",
    "Website":"Website",
    "FullAddressEnglish":"Full Address English",
    "FullAddressArabic":"Full Address Arabic",
    "Facebook":"Facebook",
    "Twitter":"Twitter",
    "Instagram":"Instagram",
    "LinkedIn":"LinkedIn",
    "Youtube":"Youtube",
    "Snapchat":"Snapchat",
    "Login":"submit",
    "companyname:":"Marketing Agancy:",
    "Country":"Country",
    "Afghanistan":"Afghanistan",
    "ÅlandIslands":"Åland Islands",
    "Albania":"Albania",
    "Algeria":"Algeria",
    "AmericanSamoa":"American Samoa",
    "Andorra":"Andorra",
    "Angola":"Angola",
    "Anguilla":"Anguilla",
    "Antarctica":"Antarctica",
    "AntiguaandBarbuda":"Antigua and Barbuda",
    "Argentina":"Argentina",
    "Armenia":"Armenia",
    "Aruba":"Aruba",
    "Australia":"Australia",
    "Austria":"Austria",
    "Azerbaijan":"Azerbaijan",
    "Bahamas":"Bahamas",
    "Bahrain":"Bahrain",
    "Bangladesh":"Bangladesh",
    "Barbados":"Barbados",
    "Belarus":"Belarus",
    "Belgium":"Belgium",
    "Belize":"Belize",
    "Benin":"Benin",
    "Bermuda":"Bermuda",
    "Bhutan":"Bhutan",
    "Bolivia":"Bolivia",
    "BosniaandHerzegovina":"Bosnia and Herzegovina",
    "Botswana":"Botswana",
    "BouvetIsland":"Bouvet Island",
    "Brazil":"Brazil",
    "BritishIndianOceanTerritory":"British Indian Ocean Territory",
    "BruneiDarussalam":"Brunei Darussalam",
    "Bulgaria":"Bulgaria",
    "BurkinaFaso":"Burkina Faso",
    "Burundi":"Burundi",
    "Cambodia":"Cambodia",
    "Cameroon":"Cameroon",
    "Canada":"Canada",
    "CapeVerde":"Cape Verde",
    "CaymanIslands":"Cayman Islands",
    "CentralAfricanRepublic":"Central African Republic",
    "Chad":"Chad",
    "Chile":"Chile",
    "China":"China",
    "ChristmasIsland":"Christmas Island",
    "Cocos (Keeling) Islands":"Cocos (Keeling) Islands",
    "Colombia":"Colombia",
    "Comoros":"Comoros",
    "Congo":"Congo",
    "Congo, The Democratic Republic of The":"Congo, The Democratic Republic of The",
    "Cook Islands":"Cook Islands",
    "Costa Rica":"Costa Rica",
    "Cote D'ivoire":"Cote D'ivoire",
    "Croatia":"Croatia",
    "Cuba":"Cuba",
    "Cyprus":"Cyprus",
    "Czech Republic":"Czech Republic",
    "Denmark":"Denmark",
    "Djibouti":"Djibouti",
    "Dominica":"Dominica",
    "Dominican Republic":"Dominican Republic",
    "Ecuador":"Ecuador",
    "Egypt":"Egypt",
    "El Salvador":"El Salvador",
    "Equatorial Guinea":"Equatorial Guinea",
    "Eritrea":"Eritrea",
    "Estonia":"Estonia",
    "Ethiopia":"Ethiopia",
    "Falkland Islands (Malvinas)":"Falkland Islands (Malvinas)",
    "Faroe Islands":"Faroe Islands",
    "Fiji":"Fiji",
    "Finland":"Finland",
    "France":"France",
    "French Guiana":"French Guiana",
    "French Polynesia":"French Polynesia",
    "French Southern Territories":"French Southern Territories",
    "Gabon":"Gabon",
    "Gambia":"Gambia",
    "Georgia":"Georgia",
    "Germany":"Germany",
    "Ghana":"Ghana",
    "Gibraltar":"Gibraltar",
    "Greece":"Greece",
    "Greenland":"Greenland",
    "Grenada":"Grenada",
    "Guadeloupe":"Guadeloupe",
    "Guam":"Guam",
    "Guatemala":"Guatemala",
    "Guernsey":"Guernsey",
    "Guinea":"Guinea",
    "Guinea-bissau":"Guinea-bissau",
    "Guyana":"Guyana",
    "Haiti":"Haiti",
    "Heard Island and Mcdonald Islands":"Heard Island and Mcdonald Islands",
    "Holy See (Vatican City State)":"Holy See (Vatican City State)",
    "Honduras":"Honduras",
    "Hong Kong":"Hong Kong",
    "Hungary":"Hungary",
    "Iceland":"Iceland",
    "India":"India",
    "Indonesia":"Indonesia",
    "Iran, Islamic Republic of":"Iran, Islamic Republic of",
    "Iraq":"Iraq",
    "Ireland":"Ireland",
    "Isle of Man":"Isle of Man",
    "Israel":"Israel",
    "Italy":"Italy",
    "Jamaica":"Jamaica",
    "Japan":"Japan",
    "Jersey":"Jersey",
    "Jordan":"Jordan",
    "Kazakhstan":"Kazakhstan",
    "Kenya":"Kenya",
    "Kiribati":"Kiribati",
    "Korea, Democratic People's Republic of":"Korea, Democratic People's Republic of",
    "Korea, Republic of":"Korea, Republic of",
    "Kuwait":"Kuwait",
    "Kyrgyzstan":"Kyrgyzstan",
    "Lao People's Democratic Republic":"Lao People's Democratic Republic",
    "Latvia":"Latvia",
    "Lebanon":"Lebanon",
    "Lesotho":"Lesotho",
    "Liberia":"Liberia",
    "Libyan Arab Jamahiriya":"Libyan Arab Jamahiriya",
    "Liechtenstein":"Liechtenstein",
    "Lithuania":"Lithuania",
    "Luxembourg":"Luxembourg",
    "Macao":"Macao",
    "Macedonia, The Former Yugoslav Republic of":"Macedonia, The Former Yugoslav Republic of",
    "Madagascar":"Madagascar",
    "Malawi":"Malawi",
    "Malaysia":"Malaysia",
    "Maldives":"Maldives",
    "Mali":"Mali",
    "Malta":"Malta",
    "Marshall Islands":"Marshall Islands",
    "Martinique":"Martinique",
    "Mauritania":"Mauritania",
    "Mauritius":"Mauritius",
    "Mayotte":"Mayotte",
    "Mexico":"Mexico",
    "Micronesia, Federated States of":"Micronesia, Federated States of",
    "Moldova, Republic of":"Moldova, Republic of",
    "Monaco":"Monaco",
    "Mongolia":"Mongolia",
    "Montenegro":"Montenegro",
    "Montserrat":"Montserrat",
    "Morocco":"Morocco",
    "Mozambique":"Mozambique",
    "Myanmar":"Myanmar",
    "Namibia":"Namibia",
    "Nauru":"Nauru",
    "Nepal":"Nepal",
    "Netherlands":"Netherlands",
    "Netherlands Antilles":"Netherlands Antilles",
    "New Caledonia":"New Caledonia",
    "New Zealand":"New Zealand",
    "Nicaragua":"Nicaragua",
    "Niger":"Niger",
    "Nigeria":"Nigeria",
    "Niue":"Niue",
    "Norfolk Island":"Norfolk Island",
    "Northern Mariana Islands":"Northern Mariana Islands",
    "Norway":"Norway",
    "Oman":"Oman",
    "Pakistan":"Pakistan",
    "Palau":"Palau",
    "Palestinian Territory, Occupieds":"Palestinian Territory, Occupied",
    "Panama":"Panama",
    "Papua New Guinea":"Papua New Guinea",
    "Paraguay":"Paraguay",
    "Peru":"Peru",
    "Philippines":"Philippines",
    "Pitcairn":"Pitcairn",
    "Poland":"Poland",
    "Portugal":"Portugal",
    "Puerto Rico":"Puerto Rico",
    "Qatar":"Qatar",
    "Reunion":"Reunion",
    "Romania":"Romania",
    "Russian Federation":"Russian Federation",
    "Rwanda":"Rwanda",
    "Saint Helena":"Saint Helena",
    "Saint Kitts and Nevis":"Saint Kitts and Nevis",
    "Saint Lucia":"Saint Lucia",
    "Saint Pierre and Miquelon":"Saint Pierre and Miquelon",
    "Saint Vincent and The Grenadines":"Saint Vincent and The Grenadines",
    "Samoa":"Samoa",
    "San Marino":"San Marino",
    "Sao Tome and Principe":"Sao Tome and Principe",
    "Saudi Arabia":"Saudi Arabia",
    "Senegal":"Senegal",
    "Serbia":"Serbia",
    "Seychelles":"Seychelles",
    "Sierra Leone":"Sierra Leone",
    "Singapore":"Singapore",
    "Slovakia":"Slovakia",
    "Slovenia":"Slovenia",
    "Solomon Islands":"Solomon Islands",
    "Somalia":"Somalia",
    "South Africa":"South Africa",
    "South Georgia and The South Sandwich Islands":"South Georgia and The South Sandwich Islands",
    "Spain":"Spain",
    "Sri Lanka":"Sri Lanka",
    "Sudan":"Sudan",
    "Suriname":"Suriname",
    "Svalbard and Jan Mayen":"Svalbard and Jan Mayen",
    "Swaziland":"Swaziland",
    "Sweden":"Sweden",
    "Switzerland":"Switzerland",
    "Syrian Arab Republic":"Syrian Arab Republic",
    "Taiwan, Province of China":"Taiwan, Province of China",
    "Tajikistan":"Tajikistan",
    "Tanzania, United Republic of":"Tanzania, United Republic of",
    "Thailand":"Thailand",
    "Timor-leste":"Timor-leste",
    "Togo":"Togo",
    "Tokelau":"Tokelau",
    "Tonga":"Tonga",
    "Trinidad and Tobago":"Trinidad and Tobago",
    "Tunisia":"Tunisia",
    "Turkey":"Turkey",
    "Turkmenistan":"Turkmenistan",
    "Turks and Caicos Islands":"Turks and Caicos Islands",
    "Tuvalu":"Tuvalu",
    "Uganda":"Uganda",
    "Ukraine":"Ukraine",
    "United Arab Emirates":"United Arab Emirates",
    "United Kingdom":"United Kingdom",
    "United States":"United States",
    "United States Minor Outlying Islands":"United States Minor Outlying Islands",
    "Uruguay":"Uruguay",
    "Uzbekistan":"Uzbekistan",
    "Vanuatu":"Vanuatu",
    "Venezuela":"Venezuela",
    "Viet Nam":"Viet Nam",
    "Virgin Islands, British":"Virgin Islands, British",
    "Virgin Islands, U.S.":"Virgin Islands, U.S.",
    "Wallis and Futuna":"Wallis and Futuna",
    "Western Sahara":"Western Sahara",
    "Yemen":"Yemen",
    "Zambia":"Zambia",
    "Zimbabwe":"Zimbabwe",
        }     
changeDirectonBtn.addEventListener('click',choiseContent);
function choiseContent(){
    console.log("click")
    var contentBtn=this.className;//e.target===this
    var ele=this;
    choiseLang(contentBtn,ele)
}
function choiseLang(contentBtn,ele){
    if(contentBtn=="English"){
        changeContent(ele,"العربيه","ltr",dataEnglish,contentBtn);
        ele.setAttribute("style","top: 85%;left: 90%;")
        loopArray(elementFloatleft,"mr-auto","ml-auto")
        loopArray(elementFloatleft,"float-right","float-left")
        loopArray(elementFloatRight,"float-left","float-right")
        loopArray(elementTxtAlign,"text-right","text-left")
    }
    else if(contentBtn=="العربيه"){
        changeContent(ele,"English","rtl",dataArabic,contentBtn);
        ele.setAttribute("style","top: 85%;left: 2%;")
        loopArray(elementFloatleft,"ml-auto","mr-auto")
        loopArray(elementFloatleft,"float-left","float-right")
        loopArray(elementFloatRight,"float-right","float-left")
        loopArray(elementTxtAlign,"text-left","text-right")
    }
}
function changeContent(element,lang,direction,objData,classBtn){
    element.innerText=lang;
    element.className=lang;
    document.querySelector("html").setAttribute("dir",direction);
    localStorage.setItem("Btn",lang);
    localStorage.setItem("ClassButton",classBtn);
    for(param in objData){
      document.getElementById(param).innerText=objData[param]  
    }
}
function getLocalStorage(){
    if(localStorage.getItem("Btn")&&localStorage.getItem("ClassButton")){
        console.log("true")
        choiseLang(localStorage.getItem("ClassButton"),changeDirectonBtn);
    }else{
        console.log("false")
        choiseLang(changeDirectonBtn.className,changeDirectonBtn);
    }
}
function loopArray(elements,remove,add){
    elements.forEach((element,index) => {
        classAddAndRemove(element,remove,add)
        console.log(index,element)
    })
}
function classAddAndRemove(ele,remove,add){
    ele.classList.remove(remove);
    ele.classList.add(add);
}